sudo: required
services: 
  - docker

before_install:
  - docker build -t naveens1726/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run naveens1726/react-test npm test -- --coverage

after_success:
  - docker build -t naveens1726/multi-client ./client
  - docker build -t naveens1726/multi-ngninx ./nginx
  - docker build -t naveens1726/multi-server ./server
  - docker build -t naveens1726/multi-worker ./worker

# log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take images and push to docker hub
  - docker push naveens1726/multi-client
  - docker push naveens1726/multi-ngninx
  - docker push naveens1726/multi-server
  - docker push naveens1726/multi-worker